### PR TITLE
Added new rounding functionality

### PR DESCRIPTION
**Pull request by yonMaor**

### CODE REVIEW

**Review by ConradSelig — CHANGES_REQUESTED** [review]
- Extra print() call in utils.py on line 19 displays None when cliStocksTracker.py imports it.
- return statement on line 14 contains an invalid call to trunc(), line should instead be `return trunc(value)`

Other than that looks good. Make those few changes and we'll merge the pull request.

**Comment by yonMaor** [comment]
Messed up a little bit because of my lack of experience with git, but I've fixed your comments

**Comment by ConradSelig** [comment]
Only way to learn. This is a great project to make those kinds of mistakes as well.

**Review by ConradSelig — APPROVED** [review]

**Comment by yonMaor** [comment]
Agreed. If you have any more issues for newbies like me let me know :)

**Pull request merged**
